### ISSUE TITLE
Problem with config <SOLVED>

### ISSUE THREAD

**Issue by ncap1980** [ronny3050/email-mirror#1]
First of all I tested with two types of email, with two-step authentication and other normal.
I can`t config the module, it give me black window. 

My file config/config.js

{
                module: 'email-mirror',
                    position: 'bottom_left',
                    header: 'Email',
                    config:{             
                         user: 'ncap24@gmail.com',
                         password: '<my pass>',
                         host: 'imap.gmail.com',
                         port: 993,
                         tls: true,
                         authTimeout: 10000,
                         numberOfEmails: 5,
                         fade: true
                }
        },

I have a cuestion.
We must also configure the file in the folder email.js module? Is the same config?

**Comment by ronny3050** [comment]
@ncap1980 looks like you have some issues with the module name 'email-mirror'. Is the name of folder 'email' and not 'email-mirror'? Your config needs to be:

```{
module: 'email',
position: 'bottom_left',
header: 'Email',
config:{

user: 'ncap24@gmail.com',
password: '',
host: 'imap.gmail.com',
port: 993,
tls: true,
authTimeout: 10000,
numberOfEmails: 5,
fade: true
}
},
```

No, your config/config.js is the main config. Everything you configure has to be in here.

**Comment by ncap1980** [comment]
thanks for responding so quickly, effectively the name of the folder module was wrong, I change the name on the module instead of the folder. now works half, he remains loaded, but it at least appears.

**Comment by ncap1980** [comment]
Good morning, Ya me everything works correctly. Set what you said and restart, and already appears look.

**Comment by Anotherthoughtkrime** [comment]
no lie im a noob, im doing my best and have great help around me, i just wanna figure it out.  i have  done everything it seems from tabs over spaces and copy and paste, re writing and having other people check it line for line . the mirror is groovy then i add this all be it my first MMM but i just cant get it. works fine then i add this and we are a no go t this module

**Comment by ronny3050** [comment]
What exactly happens? Also, please paste your config file.
