### ISSUE TITLE
Text Runover? 

### ISSUE THREAD

**Issue by ChristopherMori** [ronny3050/email-mirror#12]
Anyway i can limit the amount of text in the preview text under the subject so that it doesn't run into other modules?

**Comment by ChristopherMori** [comment]
Also I would like to orient it on the right side of MM and not the left.

**Comment by ChristopherMori** [comment]
I also see the readme file that shows the configurations you can add but i am not having much luck implementing.....

**Comment by adrianp2203** [comment]
You must change the css file.

**Comment by ronny3050** [comment]
@ChristopherMori were you able to resolve this issue?
For limiting the amount of text:
in email.js
search line 59:
`var subject = mailObj.subject.replace(/[[’"]]+/g,"");`
replace it with:
`var subject = mailObj.subject.replace(/[[’"]]+/g,"");subject = subject.substring(0,30); //This limit of 30 characters`

**Comment by ronny3050** [comment]
Fixed - `maxCharacters` controls the number of characters to display.
