### ISSUE TITLE
Refresh Emails

### ISSUE THREAD

**Issue by adrianp2203** [ronny3050/email-mirror#13]
There is no possibility to refresh the email in a interval. Maybe someone can add this feature.

**Comment by ronny3050** [comment]
The connection to email account should be always open, and it should refresh on new incoming emails.

**Comment by adrianp2203** [comment]
I mean when you have an unread Message it will display the Message. But when you read the Message, the Message is still unread and displayed. I want that the Message are not show, when you read it.

**Comment by sajuran123** [comment]
Any solution to this? :)
