### ISSUE TITLE
No email showing up on panel

### ISSUE THREAD

**Issue by sushanttheone** [ronny3050/email-mirror#14]
Hi Ronny,

Great work and a very useful module. I am facing one issue. On the panel there is no email showing up and it just says Loading........ The console displays following message.

listening for emails...
NEW MAIL
NEW MAIL
NEW MAIL
NEW MAIL
NEW MAIL
NEW MAIL
NEW MAIL
NEW MAIL
And it keeps on going in a loop showing the 'NEW MAIL' text. Can you please give some suggestions to fix this issue.

**Comment by sushanttheone** [comment]
As per on of your earlier comment for similar issue I already did this and did a reboot

If you’re using Gmail, you need to ‘set lower security for apps’ https://www.google.com/settings/security/lesssecureapps.

**Comment by sushanttheone** [comment]
I found the root cause....the inbox I was using was way to large.....is there a way to just show latest 5-10 mails irrespective of read/unread status?

**Comment by ronny3050** [comment]
There is a config parameter called `numberOfEmails` which can be used to set the number of emails to display.
