### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by edsulst** [ronny3050/email-mirror#15]
When installing this plugin a warning is showing up and the plugin seems to be failing.

npm WARN email@0.0.1 No repository field.
npm WARN email@0.0.1 No licence field.

When I add the module to the config/config.js file, my Magic Mirror if failing on loading the js file.
I'm using a Raspberry 3 and installed Magic Mirror with the auto installer from MichMich.

Please help.

**Comment by ronny3050** [comment]
Thank you for your feedback. Unfortunately, those are just warnings and your mirror is most definitely not failing because of the two warnings.

To further investigate, please post your logs here.
