### ISSUE TITLE
Limit for the width of the module

### ISSUE THREAD

**Issue by Wominator** [ronny3050/email-mirror#17]
Hi! 
Is there a possibility to limit the width of the module. When I receive mails with headers containing ten or more words, the module uses the full width of the screen an crashes other modules. (Setting position: 'top_left',) When I put in "bottom_bar" it won't align to the left.

Thanks in advance
Wominator

**Comment by ronny3050** [comment]
Should be fixed with the latest push. `maxCharacters` is set to 30 by default, change as you please.

**Comment by Wominator** [comment]
Thanks! 
I'll have a look! 
Regards
Wominator
