### ISSUE TITLE
keeps loading without showing anything

### ISSUE THREAD

**Issue by mamoun21** [ronny3050/email-mirror#18]
I'm useing Gmail, and i did authorize it for less secure apps also i limited the number of emails to 3 but it keeps loading withoud showing anything! it's not a connection error because i'm used other modules that recure connection and they are working.
PS: on the terminal it keeps saying NEW EMAIL too many times

**Comment by ronny3050** [comment]
It's very likely that you have too many unread emails which is causing a server request overload. Please try reducing the number of emails, and if it still does not work, let me know! :)

**Comment by mamoun21** [comment]
this was very helpfull thanks alot
