### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by chrisvanlaar** [ronny3050/email-mirror#2]
Hello,

When i start the mirror it works fine! 
for example i see that in the Terminal screen 3 times the text : NEW MAIL
That is correct because there are 2 new mails. but on the MM it say No new mail.

Why didn.t load it the new mails?

Thanks,
Chris

**Comment by chrisvanlaar** [comment]
It is now visible, in my config file was a , wrong.
I filled the mail setting securely good but it recieves no new mail!

Chris

**Comment by ronny3050** [comment]
Glad that got fixed. :)

**Comment by ronny3050** [comment]
Glad that got fixed. :)
