### ISSUE TITLE
newest version doesnt show anything

### ISSUE THREAD

**Issue by apm1007** [ronny3050/email-mirror#24]

**Comment by darkogor** [comment]
Change the folder module folder to be called: "email", and then "npm install" into the folder. That should make the module to work. Why it doesn't show the emails I am not sure.

**Comment by apm1007** [comment]
Thx. It is Working now. Can you Update GitHub please.

Mit freundlichen Grüßen
A. P. Mielke

______________________
Diese Nachricht ist ausschließlich für den bezeichneten
Adressaten oder dessen Vertreter bestimmt.
Sollten Sie nicht der vorgesehene Adressat dieser E-Mail
oder dessen Vertreter sein, so bitten wir Sie, sich mit
dem Absender der E-Mail in Verbindung zu setzen.
______________________
This message is exclusively for the person addressed or their
representative. If you are not the intended recipient of this message and
its contents, please notify the sender immediately.

Am 07.11.2017 2:04 nachm. schrieb "darkogor" <notifications@github.com>:
