### ISSUE TITLE
mime.extension is not a function

### ISSUE THREAD

**Issue by PhilGrue** [ronny3050/email-mirror#25]
Hi ronny3050,

thanks for the great module!! Showing my emails makes my mirror even better ;)
Unfortunetly, I have following issues with the module:
#1: When I use my outlook.office365.com account, the module doesn't refresh - so I created an account at 1&1 (one of the largest german hosting companies) and redirect my emails.
#2: Now I can see my mails on my mirror, but my pm2 log keeps showing me the errors attached below. Besides, the module shows more mails than set in "numberOfEmails:":
If set, the module does not receive any mails, but when I switch off ("//") the option "numberOfEmails" the module shows me at least 10+ mails (and that's way too much!). Shouldn't it be 5 by default?

Here is my "MagicMirror-error-0.log":
> TypeError: mime.extension is not a function
> at MailParser._generateFileName (/home/pi/MagicMirror/modules/email/node_modules/mailparser/lib/mailparser.js:1407:27)
> at MailParser._processStateHeader (/home/pi/MagicMirror/modules/email/node_modules/mailparser/lib/mailparser.js:309:61)
> at MailParser._process (/home/pi/MagicMirror/modules/email/node_modules/mailparser/lib/mailparser.js:227:22)
> at runCallback (timers.js:672:20)
> at tryOnImmediate (timers.js:645:5)
> at processImmediate [as _immediateCallback] (timers.js:617:5)

My "MagicMirror-out-0.log":
> Whoops! There was an uncaught exception...
> MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
> If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

My configuration:
```
 {
 module: 'email',
 position: 'top_left',
 header: 'Mails',
 config: {
 accounts: [
 {
 user: '**@**',
 password: '***',
 host: 'imap.1und1.de',
 port: 993,
 tls: true,
 authTimeout: 60 * 1000,
 //numberOfEmails: 5, //if set, module doesn't show anything at all!
 },
 ],
 fade: false,
 maxCharacters: 30
 }
 },
```

Do you have any ideas how to fix the module?
Thanks in advance & greetings from Germany 
Phil

**Comment by PhilGrue** [comment]
Update:
I've reset the option "numberOfEmails" to 5 and now the module shows my emails, but still more than 5...

**Comment by ronny3050** [comment]
I will confirm this. Thanks for opening this issue!

**Comment by ontjje** [comment]
ive been using this module but nothing are showing up.. can u help me?

{
		module: 'email',
                position: 'bottom_left',
                header: 'Emails',
                config: {
                    accounts: [
                      
                        {
                         user: 'rushellonpietersz@gmail.com',
                         password: 'ikbenhet',
                         host: 'imap.gmail.com',
                         port: 993,
                         tls: true,
                         authTimeout: 10000,
                         numberOfEmails: 5,
                        }
                    ],
                    fade: true,
                    maxCharacters: 30
                }
	
        },
