### ISSUE TITLE
Email not displaying

### ISSUE THREAD

**Issue by huntersiniard** [ronny3050/email-mirror#3]
I was trying to get the module to not space so far out on the display (it goes over farther than the calendar module and it doesn't look that good). I was trying to implement the same kind of setup that the default calendar module has with the string limit, but now no email display like it did before.

I assume I changed something and messed it up. Could anyone help me/anyone else having this problem with your emails going too far across the screen?

[email.txt](https://github.com/ronny3050/email-mirror/files/601862/email.txt)

**Comment by StefanBols** [comment]
Hi @huntersiniard 
Can you fork this repo and then make the changes again - so we can see it?
