### ISSUE TITLE
Showing as Email loading but no display of emails

### ISSUE THREAD

**Issue by Srinathpi** [ronny3050/email-mirror#4]
Hi I am not able to see any mails on the magic mirror,is there any setting required to get the display of mails,currently showing as email loading,please help

**Comment by shortstop929** [comment]
Having the same issue with my school gmail account. Although it works for my normal gmail account.

**Comment by ronny3050** [comment]
If you’re using Gmail, you need to ‘set lower security for apps’ https://www.google.com/settings/security/lesssecureapps.

Please let me know if that fixed the issue,

**Comment by Srinathpi** [comment]
Thank you Ronny,that is fixed now.

**Comment by ChristopherMori** [comment]
Yay! This worked for me. Just make sure you close out and reopen MM2
