### ISSUE TITLE
Multiple  emails

### ISSUE THREAD

**Issue by Jt4112** [ronny3050/email-mirror#7]
Just a suggestion/ question. Is there a way to currently add more than one email to the configuration file without  adding a new module for each separate email? I have multiple email accounts and would like to see them all in the same list.

**Comment by ronny3050** [comment]
I have thought about this. How would you like to able to distinguish between which email address a particular email is received in?

**Comment by Jt4112** [comment]
So 2 methods:
1st: you don't care, Let's say me and my gf have 3 addresses listed each. ( and we aren't using MMM-ProfileSwitcher) , The Name "Debayan Deb" would show who the email is for. It's not like I am actually checking my emails on my Mirror, just want to know if I have one or she has one. Even on my phone, I use the Combined Inbox Option to see what emails I have received, regardless of which email received them 

2nd: add an array of email addresses (could be used for method one as well), on display output a header of the email address and a list of emails, then display another one, etc.  This would be identical to having multiple email modules in the same config file, but instead all dealt with in one module. This option however while looking cleaner having separated the email accounts would indeed take up more mirror space. This would be more suitable for people who want to separate their work/personal emails.

In theory you could create a "Mode Class", one for "Combined" and one for "Separated" and let the people decide.

Just some ideas to make your Module more robust.

**Comment by reillychase** [comment]
Definitely looking for the multiple email function also. It was the first thing I thought of because like most people I have multiple work and personal email addresses. 

I second the #1 method, I dont care which address the email came in from (thats how I use my phone, it all dumps into the "All Inboxes" folder.

Would love that feature if you get around to it!

**Comment by ronny3050** [comment]
This feature has been added. Please update this module. Thank you! :)
