### ISSUE TITLE
Same email repeated several times in the list

### ISSUE THREAD

**Issue by OsmelTorres** [ronny3050/email-mirror#9]
Hi ronny 3050, thanks for so great job. I have learned a lot while installing email module in my MagicMirror. 
After install I start having an issue, the first time that I load the module everything  is fine but, when a new mail is loaded the list becomes in a little mess. Basically the same email gets consecutively repeated two, three or even four times thru the list. So if my list is 10 emails, i really see the last three repeated. 
Since i have never work with imap i am not an expert. I Just want to share the  solution that i found  but despite is working now for me, i am not really sure that this is the best way to do it.
This is what I did:

- On file **node_helper.js** _deleted the line 43_  `n.stop();`

- On file **email.js** _chage line 32_ from `if(that.payload.indexOf(m.id) == -1)`
to
 `if (that.payload.map(function(e) { return e.id; }).indexOf(m.id) == -1) `

Now I get no repeated emails and the _**listening for emails...**_ is triggered just once after NEW EMAIL is reached.

Please, if i am breaking something tell me.
Thanks for share your work.

**Comment by ronny3050** [comment]
Please update the module. :)
